// The tool bridge (D-55). A sandboxed script has no network and no filesystem beyond its granted roots, so the
// only way it reaches anything is by asking the broker — one JSON object per line, back through the same
// executor that answers a model's tool calls. Every check applies unchanged: the grant matrix, the approval
// queue, DNS pinning, the egress log, the exfiltration rule.
//
// The channel is stdout, with a per-run nonce prefix, and replies come back on stdin. The nonce is not a secret
// kept from the script — the script can read its own preamble — it is there so an ordinary `console.log` of a
// JSON object is printing rather than calling. Forging a call would gain a script nothing anyway: it can only
// name tools it was already granted, and the broker decides either way.
import { randomBytes } from 'node:crypto';
import type { ToolResult } from '../../shared/tool.js';

export interface BridgeRequest { id: string; tool: string; input: unknown }
export interface BridgeResponse { id: string; ok: boolean; output?: unknown; error?: { code: string; message: string; hint?: string } }

export const newNonce = (): string => `wb${randomBytes(9).toString('hex')}`;

/** A line of the child's stdout: either a bridge call, or output the script meant to print. */
export function readBridgeLine(nonce: string, line: string): { call: BridgeRequest } | { output: string } | { error: string } {
  if (!line.startsWith(`${nonce} `)) return { output: line };
  let raw: unknown;
  try {
    raw = JSON.parse(line.slice(nonce.length + 1));
  } catch {
    return { error: 'a bridge call must be one JSON object on one line' };
  }
  if (typeof raw !== 'object' || raw === null) return { error: 'a bridge call must be one JSON object on one line' };
  const { id, tool, input } = raw as Record<string, unknown>;
  if (typeof id !== 'string' || typeof tool !== 'string') return { error: 'a bridge call needs a string `id` and a string `tool`' };
  return { call: { id, tool, input } };
}

export function bridgeResponse(id: string, result: ToolResult): BridgeResponse {
  return result.ok
    ? { id, ok: true, output: result.output }
    : { id, ok: false, error: { code: result.error.code, message: result.error.message, ...(result.error.hint ? { hint: result.error.hint } : {}) } };
}

/**
 * The preamble every sandboxed script gets. `tools.<name>(input)` is defined for the tools this agent may
 * actually use, so a script that calls an ungranted one gets `PermissionDenied` from the broker — the same
 * answer a model gets, in the same words, recorded in the trace the same way — rather than a name that is not
 * there. `await` works at the top level of the script, because the whole thing is wrapped in a module.
 */
export function bridgePreamble(nonce: string): string {
  return `// Generated by the workbench: \`await tools['<name>'](input)\` goes back through the broker. Nothing else leaves.
// Any tool name may be called. What happens then is the broker's decision, in the same words a model would get,
// recorded in the trace the same way — a name that is not granted comes back as PermissionDenied, not as a
// function that does not exist, because "you may not" and "there is no such thing" are different answers.
const __enc = new TextEncoder();
const __dec = new TextDecoder();
const __chunk = new Uint8Array(1 << 16);
let __buffer = '';
let __seq = 0;

function __readLine() {
  for (;;) {
    const nl = __buffer.indexOf('\\n');
    if (nl !== -1) {
      const line = __buffer.slice(0, nl);
      __buffer = __buffer.slice(nl + 1);
      if (line.trim()) return line;
      continue;
    }
    const n = Deno.stdin.readSync(__chunk);
    if (n === null) throw new Error('the workbench closed the tool bridge');
    __buffer += __dec.decode(__chunk.subarray(0, n));
  }
}

// Synchronous on the wire, asynchronous to the caller: one call at a time, so an approval is one question, and
// no background reader keeps the process alive after the script is done.
function __call(tool, input) {
  const id = 'c' + (++__seq);
  Deno.stdout.writeSync(__enc.encode(${JSON.stringify(nonce)} + ' ' + JSON.stringify({ id, tool, input: input ?? {} }) + '\\n'));
  const message = JSON.parse(__readLine());
  if (message.ok) return Promise.resolve(message.output);
  const error = Object.assign(new Error(message.error.message), { code: message.error.code, hint: message.error.hint });
  return Promise.reject(error);
}

const tools = new Proxy({}, {
  get: (_target, name) => (typeof name === 'string' ? (input) => __call(name, input) : undefined),
  has: () => true,
});
`;
}
